export const data = {
  birthday: {
    dbPointLength: 0,
    view: 'date',
    fieldExtendJson: '',
    type: 'string',
    title: '出生日期',
    maxLength: 0,
    order: 8,
  },
  occupation: {
    dbPointLength: 0,
    view: 'text',
    fieldExtendJson: '',
    type: 'string',
    title: '职业',
    maxLength: 32,
    order: 26,
  },
  education: {
    dbPointLength: 0,
    view: 'list',
    dictCode: 'data_education',
    dictTable: '',
    fieldExtendJson: '',
    type: 'string',
    title: '学历',
    dictText: '',
    enum: [
      { value: '1', text: '小学', title: '小学' },
      { value: '2', text: '初中', title: '初中' },
      { value: '3', text: '高中', title: '高中' },
      { value: '4', text: '大专', title: '大专' },
      { value: '5', text: '本科', title: '本科' },
      { value: '6', text: '研究生', title: '研究生' },
      { value: '7', text: '硕士', title: '硕士' },
      { value: '8', text: '博士', title: '博士' },
      { value: '9', text: '其他', title: '其他' },
    ],
    order: 27,
  },
  personnel_picture: {
    dbPointLength: 0,
    view: 'image',
    fieldExtendJson: '',
    type: 'string',
    title: '人员图片',
    maxLength: 200,
    order: 15,
  },
  is_service_member: {
    dbPointLength: 0,
    view: 'radio',
    dictCode: 'data_is_service_member',
    dictTable: '',
    fieldExtendJson: '',
    type: 'string',
    title: '服务成员',
    dictText: '',
    enum: [
      { value: '1', text: '有', title: '有' },
      { value: '2', text: '无', title: '无' },
    ],
    order: 36,
  },
  email: {
    dbPointLength: 0,
    view: 'text',
    fieldExtendJson: '',
    pattern: '^[a-zA-Z0-9_-]+@[a-zA-Z0-9_-]+(\\.[a-zA-Z0-9_-]+)+$',
    errorInfo: '请输入正确格式的邮箱地址',
    type: 'string',
    title: '电子邮件',
    maxLength: 50,
    order: 35,
  },
  height: {
    dbPointLength: 0,
    view: 'number',
    fieldExtendJson: '',
    type: 'number',
    title: '身高(cm)',
    order: 34,
  },

  address_id: {
    view: 'hidden',
    hidden: true,
    type: 'string',
    title: 'address_id',
    order: 9,
  },
  registered_residence: {
    dbPointLength: 0,
    view: 'pca',
    fieldExtendJson: '',
    type: 'string',
    title: '户籍地',
    maxLength: 100,
    order: 18,
  },

  remarks: {
    dbPointLength: 0,
    view: 'textarea',
    fieldExtendJson: '',
    type: 'string',
    title: '备注',
    maxLength: 200,
    order: 41,
  },
  
};
