export const data = {
  birthday: {
    dbPointLength: 0,
    view: 'date',
    fieldExtendJson: '',
    type: 'string',
    title: '出生日期',
    maxLength: 0,
    order: 8,
  },
  occupation: {
    dbPointLength: 0,
    view: 'text',
    fieldExtendJson: '',
    type: 'string',
    title: '职业',
    maxLength: 32,
    order: 26,
  },
  education: {
    dbPointLength: 0,
    view: 'list',
    dictCode: 'data_education',
    dictTable: '',
    fieldExtendJson: '',
    type: 'string',
    title: '学历',
    dictText: '',
    enum: [
      { value: '1', text: '小学', title: '小学' },
      { value: '2', text: '初中', title: '初中' },
      { value: '3', text: '高中', title: '高中' },
      { value: '4', text: '大专', title: '大专' },
      { value: '5', text: '本科', title: '本科' },
      { value: '6', text: '研究生', title: '研究生' },
      { value: '7', text: '硕士', title: '硕士' },
      { value: '8', text: '博士', title: '博士' },
      { value: '9', text: '其他', title: '其他' },
    ],
    order: 27,
  },
  building_address_info: {
    dbPointLength: 0,
    popupMulti: false,
    view: 'popup',
    code: 'data_address',
    orgFields: 'id,address_info,sys_org_code',
    fieldExtendJson: '{"popupMulti":false}',
    type: 'string',
    title: '现住地址',
    order: 9,
    destFields: 'address_id,building_address_info,sys_org_code',
  },
  sys_org_code: {
    dbPointLength: 0,
    view: 'text',
    ui: { widgetattrs: { disabled: true } },
    fieldExtendJson: '',
    type: 'string',
    title: '所属区域',
    maxLength: 64,
    order: 10,
  },
  landline_number: {
    dbPointLength: 0,
    view: 'text',
    fieldExtendJson: '',
    type: 'string',
    title: '座机电话',
    maxLength: 20,
    order: 28,
  },
  nation: {
    dbPointLength: 0,
    view: 'list',
    dictCode: 'data_nation',
    dictTable: '',
    fieldExtendJson: '',
    type: 'string',
    title: '民族',
    dictText: '',
    enum: [
      { value: '1', text: '汉族', title: '汉族' },
      { value: '2', text: '苗族', title: '苗族' },
    ],
    order: 29,
  },
  occupational_category: {
    dbPointLength: 0,
    view: 'list',
    dictCode: 'data_occupational_category',
    dictTable: '',
    fieldExtendJson: '',
    type: 'string',
    title: '职业类别',
    dictText: '',
    enum: [
      { value: '1', text: '政府从业人员', title: '政府从业人员' },
      { value: '2', text: '高新技术人员', title: '高新技术人员' },
      { value: '3', text: '其他', title: '其他' },
    ],
    order: 38,
  },
  registered_address_info: {
    dbPointLength: 0,
    view: 'text',
    fieldExtendJson: '',
    type: 'string',
    title: '户籍门(楼)详址',
    maxLength: 100,
    order: 20,
  },
  id_card: {
    dbPointLength: 0,
    view: 'text',
    fieldExtendJson: '',
    pattern: 'only',
    errorInfo: '',
    type: 'string',
    title: '证件号码',
    maxLength: 32,
    order: 14,
  },
  personnel_picture: {
    dbPointLength: 0,
    view: 'image',
    fieldExtendJson: '',
    type: 'string',
    title: '人员图片',
    maxLength: 200,
    order: 15,
  },
  name_used_before: {
    dbPointLength: 0,
    view: 'text',
    fieldExtendJson: '',
    type: 'string',
    title: '曾用名',
    maxLength: 20,
    order: 17,
  },
  is_service_member: {
    dbPointLength: 0,
    view: 'radio',
    dictCode: 'data_is_service_member',
    dictTable: '',
    fieldExtendJson: '',
    type: 'string',
    title: '服务成员',
    dictText: '',
    enum: [
      { value: '1', text: '有', title: '有' },
      { value: '2', text: '无', title: '无' },
    ],
    order: 36,
  },
  service_premises: {
    dbPointLength: 0,
    view: 'text',
    fieldExtendJson: '',
    type: 'string',
    title: '服务处所',
    maxLength: 50,
    order: 39,
  },
  no_room_reason: {
    dbPointLength: 0,
    view: 'text',
    fieldExtendJson: '',
    type: 'string',
    title: '无房原因',
    maxLength: 100,
    order: 23,
  },
  work_units: {
    dbPointLength: 0,
    view: 'text',
    fieldExtendJson: '',
    type: 'string',
    title: '工作单位',
    maxLength: 32,
    order: 25,
  },
  other_address: {
    dbPointLength: 0,
    view: 'text',
    fieldExtendJson: '',
    type: 'string',
    title: '其他地址',
    maxLength: 50,
    order: 24,
  },
  household_status: {
    dbPointLength: 0,
    view: 'list',
    dictCode: 'data_household_status',
    dictTable: '',
    fieldExtendJson: '',
    type: 'string',
    title: '人户状态',
    dictText: '',
    enum: [
      { value: '1', text: '一致', title: '一致' },
      { value: '2', text: '不一致', title: '不一致' },
    ],
    order: 40,
  },
  audit: {
    dbPointLength: 0,
    view: 'list',
    ui: { widgetattrs: { disabled: true } },
    dictCode: 'data_population_audit',
    dictTable: '',
    fieldExtendJson: '',
    type: 'string',
    title: '是否审核',
    dictText: '',
    enum: [
      { value: '1', text: '已审核', title: '已审核' },
      { value: '2', text: '未审核', title: '未审核' },
    ],
    order: 42,
    defVal: '2',
  },
  current_residence: {
    dbPointLength: 0,
    view: 'text',
    fieldExtendJson: '',
    type: 'string',
    title: '现住门(楼)详址',
    maxLength: 100,
    order: 22,
  },
  blood_type: {
    dbPointLength: 0,
    view: 'list',
    dictCode: 'data_blood_type',
    dictTable: '',
    fieldExtendJson: '',
    type: 'string',
    title: '血型',
    dictText: '',
    enum: [
      { value: '1', text: 'A型', title: 'A型' },
      { value: '2', text: 'B型', title: 'B型' },
      { value: '3', text: 'O型', title: 'O型' },
      { value: '4', text: 'AB型', title: 'AB型' },
    ],
    order: 32,
  },
  latest_service_time: {
    dbPointLength: 0,
    view: 'date',
    fieldExtendJson: '',
    type: 'string',
    title: '服务时间',
    maxLength: 0,
    order: 37,
  },
  email: {
    dbPointLength: 0,
    view: 'text',
    fieldExtendJson: '',
    pattern: '^[a-zA-Z0-9_-]+@[a-zA-Z0-9_-]+(\\.[a-zA-Z0-9_-]+)+$',
    errorInfo: '请输入正确格式的邮箱地址',
    type: 'string',
    title: '电子邮件',
    maxLength: 50,
    order: 35,
  },
  height: {
    dbPointLength: 0,
    view: 'number',
    fieldExtendJson: '',
    type: 'number',
    title: '身高(cm)',
    order: 34,
  },
  politic_countenance: {
    dbPointLength: 0,
    view: 'list',
    dictCode: 'data_politic_countenance',
    dictTable: '',
    fieldExtendJson: '',
    type: 'string',
    title: '政治面貌',
    dictText: '',
    enum: [
      { value: '1', text: '中国共产党党员', title: '中国共产党党员' },
      { value: '2', text: '中国共产党预备党员', title: '中国共产党预备党员' },
      { value: '3', text: '中国共产主义青年团团员', title: '中国共产主义青年团团员' },
      {
        value: '4',
        text: '中国国民党革命委员会会员',
        title: '中国国民党革命委员会会员',
      },
      { value: '5', text: '中国民主同盟盟员', title: '中国民主同盟盟员' },
      { value: '6', text: '中国民主建国会会员', title: '中国民主建国会会员' },
      { value: '7', text: '中国民主促进会会员', title: '中国民主促进会会员' },
      { value: '8', text: '中国农上民主党党员', title: '中国农上民主党党员' },
      { value: '9', text: '中国致公党党员', title: '中国致公党党员' },
      { value: '10', text: '九三学社社员', title: '九三学社社员' },
      { value: '11', text: '九三学社社员', title: '九三学社社员' },
      { value: '12', text: '无党派民主人士群众', title: '无党派民主人士群众' },
      { value: '13', text: '未知或其他', title: '未知或其他' },
    ],
    order: 30,
  },
  sex: {
    dbPointLength: 0,
    view: 'list',
    dictCode: 'sex',
    dictTable: '',
    fieldExtendJson: '',
    type: 'string',
    title: '性别',
    dictText: '',
    enum: [
      { value: '0', text: '未知', title: '未知' },
      { value: '1', text: '男', title: '男' },
      { value: '2', text: '女', title: '女' },
    ],
    order: 12,
  },
  address_id: {
    view: 'hidden',
    hidden: true,
    type: 'string',
    title: 'address_id',
    order: 9,
  },
  religious_belief: {
    dbPointLength: 0,
    view: 'list',
    dictCode: 'data_religious_belief',
    dictTable: '',
    fieldExtendJson: '',
    type: 'string',
    title: '宗教信仰',
    dictText: '',
    enum: [
      { value: '1', text: '无宗教信仰', title: '无宗教信仰' },
      { value: '2', text: '佛教', title: '佛教' },
      { value: '3', text: '喇叭教', title: '喇叭教' },
      { value: '4', text: '道教', title: '道教' },
      { value: '5', text: '天主教', title: '天主教' },
      { value: '6', text: '基督教', title: '基督教' },
      { value: '7', text: '东正教', title: '东正教' },
      { value: '8', text: '伊斯兰教', title: '伊斯兰教' },
      { value: '9', text: '未知或其他', title: '未知或其他' },
    ],
    order: 33,
  },
  household_registration_category: {
    dbPointLength: 0,
    view: 'list',
    dictCode: 'data_household_registration_category',
    dictTable: '',
    fieldExtendJson: '',
    type: 'string',
    title: '户口类别',
    dictText: '',
    enum: [
      { value: '1', text: '户籍人口', title: '户籍人口' },
      { value: '2', text: '流动人口', title: '流动人口' },
    ],
    order: 11,
  },
  native_place: {
    dbPointLength: 0,
    view: 'text',
    fieldExtendJson: '',
    type: 'string',
    title: '籍贯',
    maxLength: 32,
    order: 19,
  },
  registered_residence: {
    dbPointLength: 0,
    view: 'pca',
    fieldExtendJson: '',
    type: 'string',
    title: '户籍地',
    maxLength: 100,
    order: 18,
  },
  marital_status: {
    dbPointLength: 0,
    view: 'list',
    dictCode: 'data_marital_status',
    dictTable: '',
    fieldExtendJson: '',
    type: 'string',
    title: '婚姻状况',
    dictText: '',
    enum: [
      { value: '1', text: '未婚', title: '未婚' },
      { value: '2', text: '已婚', title: '已婚' },
      { value: '3', text: '初婚', title: '初婚' },
      { value: '4', text: '再婚', title: '再婚' },
      { value: '5', text: '复婚', title: '复婚' },
      { value: '6', text: '丧偶', title: '丧偶' },
      { value: '7', text: '离婚', title: '离婚' },
      { value: '8', text: '未知', title: '未知' },
    ],
    order: 31,
  },
  name: {
    dbPointLength: 0,
    view: 'text',
    fieldExtendJson: '',
    type: 'string',
    title: '姓名',
    maxLength: 32,
    order: 7,
  },
  phone_number: {
    dbPointLength: 0,
    view: 'text',
    fieldExtendJson: '',
    pattern: '^1[3456789]\\d{9}$',
    errorInfo: '请输入正规的手机号码',
    type: 'string',
    title: '联系手机',
    maxLength: 20,
    order: 13,
  },
  registered_police_station: {
    dbPointLength: 0,
    view: 'text',
    fieldExtendJson: '',
    type: 'string',
    title: '户籍派出所',
    maxLength: 100,
    order: 21,
  },
  remarks: {
    dbPointLength: 0,
    view: 'textarea',
    fieldExtendJson: '',
    type: 'string',
    title: '备注',
    maxLength: 200,
    order: 41,
  },
  degree_of_concern: {
    dbPointLength: 0,
    view: 'list',
    dictCode: 'data_degree_of_concern',
    dictTable: '',
    fieldExtendJson: '',
    type: 'string',
    title: '关注程度',
    dictText: '',
    enum: [
      { value: '1', text: '一般', title: '一般' },
      { value: '2', text: '中等', title: '中等' },
      { value: '3', text: '严重', title: '严重' },
      { value: '4', text: '其他', title: '其他' },
    ],
    order: 16,
  },
};
