const data = {
  success: true,
  message: '查询成功',
  code: 200,
  result: {
    allAuth: [
      { action: 'online:goGenerateCode', describe: '代码生成按钮', type: '1', status: '1' },
      { action: 'user:add', describe: '添加按钮', type: '1', status: '1' },
      { action: 'user:edit', describe: '用户编辑', type: '1', status: '1' },
      { action: 'user:sex', describe: '表单性别可见', type: '1', status: '1' },
      { action: 'user:form:birthday', describe: '禁用生日字段', type: '2', status: '1' },
      { action: 'user:list', describe: '测试数据', type: '1', status: '1' },
      { action: 'user:custom_add', describe: '新增', type: '1', status: '1' },
      { action: 'user:custom_batch_delete', describe: '删除', type: '1', status: '1' },
      { action: 'user:custom_detail', describe: '详情', type: '1', status: '1' },
      { action: 'user:custom_delete', describe: '单个删除', type: '1', status: '1' },
      { action: 'task_template_add', describe: '新增', type: '1', status: '1' },
      { action: 'task_template_update', describe: '主表编辑', type: '1', status: '1' },
      { action: 'task_template_delete', describe: '主表删除', type: '1', status: '1' },
      { action: 'task_template_son_add', describe: '附表新增', type: '1', status: '1' },
      {
        action: 'task_template_son_batch_delete',
        describe: '附表批量删除',
        type: '1',
        status: '1',
      },
      { action: 'task_template_son_update', describe: '附表编辑', type: '1', status: '1' },
      {
        action: 'task_template_son_delete',
        describe: '附表单个删除',
        type: '1',
        status: '1',
      },
      { action: 'user:form:phone', describe: '手机号禁用', type: '2', status: '1' },
    ],
    auth: [
      { action: 'task_template_add', describe: '新增', type: '1' },
      { action: 'user:custom_add', describe: '新增', type: '1' },
      { action: 'task_template_son_add', describe: '附表新增', type: '1' },
      { action: 'task_template_son_delete', describe: '附表单个删除', type: '1' },
      { action: 'user:custom_detail', describe: '详情', type: '1' },
      { action: 'task_template_update', describe: '主表编辑', type: '1' },
      { action: 'task_template_son_batch_delete', describe: '附表批量删除', type: '1' },
      { action: 'user:custom_delete', describe: '单个删除', type: '1' },
      { action: 'task_template_delete', describe: '主表删除', type: '1' },
      { action: 'task_template_son_update', describe: '附表编辑', type: '1' },
      { action: 'user:custom_batch_delete', describe: '删除', type: '1' },
      { action: 'user:add', describe: '添加按钮', type: '1' },
      { action: 'user:form:phone', describe: '手机号禁用', type: '2' },
      { action: 'online:goGenerateCode', describe: '代码生成按钮', type: '1' },
      { action: 'user:form:birthday', describe: '禁用生日字段', type: '2' },
      { action: 'user:edit', describe: '用户编辑', type: '1' },
      { action: 'user:list', describe: '测试数据', type: '1' },
      { action: 'user:sex', describe: '表单性别可见', type: '1' },
    ],
    menu: [
      {
        redirect: null,
        path: '/mobile',
        component: 'LAYOUT',
        route: '0',
        children: [
          {
            path: 'multiportMenu/index',
            component: '/basiceNine/multiportMenu/index',
            route: '1',
            children: [
              {
                path: '/basiceNine/index/index',
                component: 'index',
                route: '1',
                children: [
                  {
                    path: '/basiceNine/home/home',
                    component: 'home',
                    route: '0',
                    children: [
                      {
                        path: '/collectInfo',
                        component: 'collectInfo',
                        route: '0',
                        children: [
                          {
                            path: '/basiceNine/housingInfo/index',
                            component: 'housingInfoList',
                            route: '1',
                            meta: {
                              keepAlive: false,
                              internalOrExternal: false,
                              icon: 'home_icon_syfw@2x.png',
                              componentName: 'housingInfoList',
                              title: '房屋管理',
                            },
                            name: 'pages-housingInfo-index',
                            id: '1453647567604350978',
                          },
                          {
                            path: '/basiceNine/common/helloWorld',
                            component: 'helloWorld',
                            route: '1',
                            meta: {
                              keepAlive: false,
                              internalOrExternal: false,
                              icon: 'logo.png',
                              componentName: 'helloWorld',
                              title: '重点单位管理',
                            },
                            name: 'pages-common-helloWorld',
                            id: '1453648501713600514',
                          },
                          {
                            path: '/basiceNine/addrInfo/index',
                            component: 'addrInfoList',
                            route: '1',
                            meta: {
                              keepAlive: false,
                              internalOrExternal: false,
                              icon: 'home_icon_dzk@2x.png',
                              componentName: 'addrInfoList',
                              title: '地址库',
                            },
                            name: 'pages-addrInfo-index',
                            id: '1453647835821703170',
                          },
                          {
                            path: '/basiceNine/basicInfo/modules',
                            component: 'modules',
                            route: '1',
                            meta: {
                              keepAlive: false,
                              internalOrExternal: false,
                              icon: 'home_icon_syrk@2x.png',
                              componentName: 'modules',
                              title: '实有人口',
                            },
                            name: 'pages-basicInfo-modules',
                            id: '1450786203155066882',
                          },
                          {
                            path: '/basiceNine/keyPlaces/index',
                            component: 'keyPlaces',
                            route: '1',
                            meta: {
                              keepAlive: false,
                              internalOrExternal: false,
                              icon: 'logo.png',
                              componentName: 'keyPlaces',
                              title: '重点场所',
                            },
                            name: 'pages-keyPlaces-index',
                            id: '1453648659348127745',
                          },
                          {
                            path: '/basiceNine/organization/index',
                            component: 'organization',
                            route: '1',
                            meta: {
                              keepAlive: false,
                              internalOrExternal: false,
                              icon: 'home_icon_syzz@2x.png',
                              componentName: 'organization',
                              title: '组织机构',
                            },
                            name: 'pages-organization-index',
                            id: '1453648101996429314',
                          },
                          {
                            path: '/basiceNine/specialPopulations/index',
                            component: 'specialPopulations',
                            route: '1',
                            meta: {
                              keepAlive: false,
                              internalOrExternal: false,
                              icon: 'home_icon_tsrq@2x.png',
                              componentName: 'specialPopulations',
                              title: '特殊人群',
                            },
                            name: 'pages-specialPopulations-index',
                            id: '1450786342213021697',
                          },
                          {
                            path: '/basiceNine/workflow/index',
                            component: 'workflow',
                            route: '1',
                            meta: {
                              keepAlive: false,
                              internalOrExternal: false,
                              icon: 'logo.png',
                              componentName: 'workflow',
                              title: '问题管理',
                            },
                            name: 'pages-workflow-index',
                            id: '1453648785269522434',
                          },
                        ],
                        meta: {
                          keepAlive: false,
                          internalOrExternal: false,
                          componentName: 'collectInfo',
                          title: '信息采集',
                        },
                        name: 'collectInfo',
                        id: '1450785895339290625',
                      },
                      {
                        path: '/gridEvent',
                        component: 'gridEvent',
                        route: '0',
                        meta: {
                          keepAlive: false,
                          internalOrExternal: false,
                          componentName: 'gridEvent',
                          title: '网格事件',
                        },
                        name: 'gridEvent',
                        id: '1450785720344539137',
                      },
                    ],
                    meta: {
                      keepAlive: false,
                      internalOrExternal: false,
                      componentName: 'home',
                      title: '首页',
                    },
                    name: 'pages-home-home',
                    id: '1450785216478605314',
                  },
                  {
                    path: '/basiceNine/user/people',
                    component: 'people',
                    route: '0',
                    meta: {
                      keepAlive: false,
                      internalOrExternal: false,
                      componentName: 'people',
                      title: '个人中心',
                    },
                    name: 'pages-user-people',
                    id: '1450785216583462913',
                  },
                ],
                meta: {
                  keepAlive: false,
                  internalOrExternal: false,
                  componentName: 'index',
                  title: '移动办公系统',
                },
                name: 'pages-index-index',
                id: '1450784682879250434',
              },
              {
                path: '/pagesLead/index/index',
                component: 'leadIndex',
                route: '1',
                meta: {
                  keepAlive: false,
                  internalOrExternal: false,
                  componentName: 'leadIndex',
                  title: '领导移动端',
                },
                name: 'pagesLead-index-index',
                id: '1450785132970012674',
              },
            ],
            meta: {
              keepAlive: false,
              internalOrExternal: false,
              componentName: 'multiportMenu',
              title: '主菜单',
            },
            name: 'pages-multiportMenu-index',
            id: '1450784355488657410',
          },
        ],
        meta: {
          keepAlive: false,
          internalOrExternal: false,
          icon: 'tablet',
          componentName: 'mobile',
          title: '移动端',
        },
        name: 'mobile',
        id: '1443133490369105921',
      },
    ],
  },
  timestamp: 1635611770185,
};

export default data;
